# Generated by Django 4.1.1 on 2022-10-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_measurement_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
