# Generated by Django 4.1.1 on 2022-10-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0007_remove_sensor_measures_measurement_sensor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensormeasurements',
            name='temperature',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
