# Generated by Django 4.1.1 on 2022-10-01 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0008_sensormeasurements_temperature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='temperature',
        ),
    ]
