# Generated by Django 4.1.1 on 2022-10-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0009_remove_measurement_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='temperature',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SensorMeasurements',
        ),
    ]
