# Generated by Django 4.1.1 on 2022-10-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0010_measurement_temperature_delete_sensormeasurements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='measure_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
