# Generated by Django 4.1.1 on 2022-09-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_phone_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
