# Generated by Django 4.1.1 on 2022-09-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_phone_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='image',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to=''),
        ),
    ]
