# Generated by Django 4.1.1 on 2022-09-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0004_phone_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='release_date',
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
    ]
