# Generated by Django 4.1.1 on 2022-09-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0005_phone_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='lte_exists',
            field=models.BooleanField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='image',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to=''),
        ),
    ]
